name: chemprop_solvation

channels:
  - rdkit
  - pytorch
  - conda-forge

dependencies:
  - gunicorn
  - rdkit
  - pytorch
  - torchvision
  - flask
  - hyperopt
  - numpy
  - scikit-learn
  - scipy
  - tensorflow
  - tensorboardX
  - tqdm
